package url

import (
	context "context"

	domainurl "github.com/KolManis/shortlink/internal/domain/url"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx
func (_m *MockRepository) BeginTx(ctx context.Context) (pgx.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockRepository_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) BeginTx(ctx interface{}) *MockRepository_BeginTx_Call {
	return &MockRepository_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx)}
}

func (_c *MockRepository_BeginTx_Call) Run(run func(ctx context.Context)) *MockRepository_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_BeginTx_Call) Return(_a0 pgx.Tx, _a1 error) *MockRepository_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_BeginTx_Call) RunAndReturn(run func(context.Context) (pgx.Tx, error)) *MockRepository_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, tx, _a2
func (_m *MockRepository) Create(ctx context.Context, tx pgx.Tx, _a2 *domainurl.Url) (int64, error) {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, *domainurl.Url) (int64, error)); ok {
		return rf(ctx, tx, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, *domainurl.Url) int64); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, *domainurl.Url) error); ok {
		r1 = rf(ctx, tx, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - _a2 *domainurl.Url
func (_e *MockRepository_Expecter) Create(ctx interface{}, tx interface{}, _a2 interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, _a2)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, tx pgx.Tx, _a2 *domainurl.Url)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(*domainurl.Url))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 int64, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, pgx.Tx, *domainurl.Url) (int64, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOriginalURL provides a mock function with given fields: ctx, originalURL
func (_m *MockRepository) GetByOriginalURL(ctx context.Context, originalURL string) (*domainurl.Url, error) {
	ret := _m.Called(ctx, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for GetByOriginalURL")
	}

	var r0 *domainurl.Url
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domainurl.Url, error)); ok {
		return rf(ctx, originalURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domainurl.Url); ok {
		r0 = rf(ctx, originalURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainurl.Url)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByOriginalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOriginalURL'
type MockRepository_GetByOriginalURL_Call struct {
	*mock.Call
}

// GetByOriginalURL is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
func (_e *MockRepository_Expecter) GetByOriginalURL(ctx interface{}, originalURL interface{}) *MockRepository_GetByOriginalURL_Call {
	return &MockRepository_GetByOriginalURL_Call{Call: _e.mock.On("GetByOriginalURL", ctx, originalURL)}
}

func (_c *MockRepository_GetByOriginalURL_Call) Run(run func(ctx context.Context, originalURL string)) *MockRepository_GetByOriginalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetByOriginalURL_Call) Return(_a0 *domainurl.Url, _a1 error) *MockRepository_GetByOriginalURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByOriginalURL_Call) RunAndReturn(run func(context.Context, string) (*domainurl.Url, error)) *MockRepository_GetByOriginalURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetByShortCode provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetByShortCode(ctx context.Context, id string) (*domainurl.Url, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByShortCode")
	}

	var r0 *domainurl.Url
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domainurl.Url, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domainurl.Url); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainurl.Url)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByShortCode'
type MockRepository_GetByShortCode_Call struct {
	*mock.Call
}

// GetByShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetByShortCode(ctx interface{}, id interface{}) *MockRepository_GetByShortCode_Call {
	return &MockRepository_GetByShortCode_Call{Call: _e.mock.On("GetByShortCode", ctx, id)}
}

func (_c *MockRepository_GetByShortCode_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetByShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetByShortCode_Call) Return(_a0 *domainurl.Url, _a1 error) *MockRepository_GetByShortCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByShortCode_Call) RunAndReturn(run func(context.Context, string) (*domainurl.Url, error)) *MockRepository_GetByShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementClicks provides a mock function with given fields: ctx, id
func (_m *MockRepository) IncrementClicks(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementClicks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_IncrementClicks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementClicks'
type MockRepository_IncrementClicks_Call struct {
	*mock.Call
}

// IncrementClicks is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) IncrementClicks(ctx interface{}, id interface{}) *MockRepository_IncrementClicks_Call {
	return &MockRepository_IncrementClicks_Call{Call: _e.mock.On("IncrementClicks", ctx, id)}
}

func (_c *MockRepository_IncrementClicks_Call) Run(run func(ctx context.Context, id string)) *MockRepository_IncrementClicks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_IncrementClicks_Call) Return(_a0 error) *MockRepository_IncrementClicks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_IncrementClicks_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_IncrementClicks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateShortCode provides a mock function with given fields: ctx, tx, id, shortCode
func (_m *MockRepository) UpdateShortCode(ctx context.Context, tx pgx.Tx, id int64, shortCode string) error {
	ret := _m.Called(ctx, tx, id, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for UpdateShortCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64, string) error); ok {
		r0 = rf(ctx, tx, id, shortCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateShortCode'
type MockRepository_UpdateShortCode_Call struct {
	*mock.Call
}

// UpdateShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id int64
//   - shortCode string
func (_e *MockRepository_Expecter) UpdateShortCode(ctx interface{}, tx interface{}, id interface{}, shortCode interface{}) *MockRepository_UpdateShortCode_Call {
	return &MockRepository_UpdateShortCode_Call{Call: _e.mock.On("UpdateShortCode", ctx, tx, id, shortCode)}
}

func (_c *MockRepository_UpdateShortCode_Call) Run(run func(ctx context.Context, tx pgx.Tx, id int64, shortCode string)) *MockRepository_UpdateShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_UpdateShortCode_Call) Return(_a0 error) *MockRepository_UpdateShortCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateShortCode_Call) RunAndReturn(run func(context.Context, pgx.Tx, int64, string) error) *MockRepository_UpdateShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
